### PR TITLE
Jekyll升级3.0本地无法预览解决方案

### PR DESCRIPTION
**Pull request by voleking**

### CODE REVIEW

**Comment by Huxpro** [comment]
@voleking  
Many people report this issue and I don't know how to handle it. Thank you for that!

**Comment by voleking** [comment]
@Huxpro 
By the way, we should install **jekyll-paginate** first.
`$ sudo gem install jekyll-paginate`
then add gems: **[jekyll-paginate]** into **_config.yml**
If we didn't install **pygments.rb**
`_$ gem install pygments.rb_`
`gem 'pygments.rb'`
I fond this solution from [azeril.me](http://azeril.me/blog/Repair-Jekyll-Serve-Problems.html)
Hope help.

**Comment by Huxpro** [comment]
@voleking 
OMG. I hate that.....I am so so worried about how to add bunch of those things into my document T.T
Anyway, thank you!

**Comment by voleking** [comment]
My pleasure.

**Pull request merged**
