### PR TITLE
SSR Edition

### PR DESCRIPTION
**Pull request by LucasIcarus**
This pr is kind of a Reconstruction for this blog system by React.js Server Side Rendering and some other techs... 

Maybe new a branch and make this pr as a feature supply?

Happy Day!

### CODE REVIEW

**Comment by LucasIcarus** [comment]
the name in package.json should be hux-blog-feature-ssr, ':' will cause an error when run the script 'start'

**Comment by Huxpro** [comment]
@LucasIcarus 
Sorry for pending it so so long since I dont have time to really dive into code and review it these days and near future, possibly. But I really appreciate your work and this is absolutely awesome!

Since this is SSR, it obviously require own server to host it. So I guess it may be a little bit confusing to merge it as a branch of this repo, for now. But yep this is definitely a killer feature. And maybe we can see this as a more independent project, instead?

So, Would you mind hosting it as a separate repo? Im glad to refer it in the documentation ;)

**Comment by Huxpro** [comment]
@LucasIcarus 
For nowadays' usage, I just add the ssr branch of your fork repo to readme. 
Check out https://github.com/Huxpro/huxpro.github.io#porting

**Comment by LucasIcarus** [comment]
@Huxpro For now, it is semifinished and not qualified as a independent project also a request to merge. My pull is aimed to seek some advices to carry through. So, any guides?

**Comment by LucasIcarus** [comment]
@Huxpro

**Comment by LucasIcarus** [comment]
@Huxpro 
I finish the catalog and comment part, so here left the last issue about the keynote layout. This little elf based on Reveal.js, is integrating it into React.js necessary?  Maybe it's too heavy after bundle? 
Without doubt that it is super cooooool! I decide working on it these days, leave some feedback when u r free, 祝好~

**Comment by LucasIcarus** [comment]
@Huxpro  I move the pr to the master branch of the forked repo, the link in README.md now need modify.

**Pull request closed without merging**
